blood/urls.py
from django.urls import path
from django.views.generic import ListView
from .models import Blood

app_name = 'blood'

urlpatterns = [
    path('', ListView.as_view(model=Blood), name='home'),
]

hmsproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
    path('patients/', include('patients.urls')),
    path('blood/', include('blood.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomeView

app_name = 'pages'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

patients/urls.py
from django.urls import path

from patients import views
from .views import HomeView, CaseDetailView

app_name = 'patients'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('cases/<int:pk>/', CaseDetailView.as_view(), name='case-detail'),
    # path('payments/', views.PaymentView.as_view(), name='payments')
]

templates/includes/ambulance_modal.html
<div class="modal fade" id="ambulance-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ambulance Services</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
          <p class="text-danger">
              Emergency Ambulance Number
          </p>
          <a class="text-dark" href="tel:123456789">123456789</a>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

templates/includes/carousel.html
{% load static %}
<div class="bd-example">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/carousel/2.jpg' %}" class="d-block w-100" alt="..." style="height: 85vh;">
        <div class="carousel-caption d-none d-md-block">
          <h4>Ralph Marston</h4>
            <p class="lead"><strong>Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit. Then get back to work.</strong></p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/carousel/1.jpg' %}" class="d-block w-100" alt="..." style="height: 85vh;">
        <div class="carousel-caption d-none d-md-block">
          <h4>Denis Waitley</h4>
            <p class="lead"><strong>Time and health are two precious assets that we don't recognize and appreciate until they have been depleted.</strong></p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/carousel/3.jpg' %}" class="d-block w-100" alt="..." style="height: 85vh;">
        <div class="carousel-caption d-none d-md-block">
          <h4>Mark Twain</h4>
            <p class="lead"><strong>The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not.</strong></p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

templates/includes/footer.html
<div class="text-center bg-dark text-white p-3">
    <small style="font-family: 'Exo', sans-serif;">Made with &#9749; and &#x2764; by <a
            target="_blank" class="text-white" href="https://techzia.in/">HospoZia</a></small>
</div>

templates/includes/message.html
{% if messages %}
    <div class="text-center bg-light p-3">
        {% for message in messages %}
            <span class="lead">{{ message }}</span>
        {% endfor %}
    </div>
{% endif %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="{% if not user.is_authenticated %}{% url 'pages:home' %}{% else %}{% url 'patients:home' %}{% endif %}">{% if not user.is_authenticated %}HospoZia{% else %}Patient
        Administration{% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navBar" aria-controls="navBar"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navBar">
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link active" href="

                    {% if not user.is_authenticated %}{% url 'pages:home' %}{% else %}{% url 'patients:home' %}{% endif %}">
                {% if user.is_authenticated %}Dashboard{% else %}Home{% endif %}</a>
            {% if not user.is_authenticated %}
                <a class="nav-item nav-link {% if request.path == '/' %}smooth{% endif %}" href="{% if not request.path == '/' %}/#departments{% else %}#departments{% endif %}">Departments</a>
                <a class="nav-item nav-link {% if request.path == '/' %}smooth{% endif %}" href="{% if not request.path == '/' %}/#appointments{% else %}#appointments{% endif %}">Appointments</a>
                <a class="nav-item nav-link {% if request.path == '/' %}smooth{% endif %}" href="{% if not request.path == '/' %}/#contact-us{% else %}#contact-us{% endif %}">Contact Us</a>
                <a class="nav-item nav-link" href="{% url 'blood:home' %}">Blood Bank</a>
                <a class="nav-item nav-link" href="#ambulance-modal" data-toggle="modal">Ambulance</a>
{#            {% else %}#}
{#                <a class="nav-item nav-link" href="#">Bills</a>#}
{#                <a class="nav-item nav-link" href="#">Payments</a>#}
            {% endif %}
        </div>
    </div>
</nav>

templates/includes/topbar.html
<div id="topbar" class="bg-danger d-flex flex-row-reverse py-3 px-4 justify-content-between">
    {% if not request.user.is_authenticated %}
        <div>
            <a href="{% url 'login' %}" class="text-uppercase text-white text-decoration-none small-text">Sign in <i
                    class="fa fa-sign-in-alt"></i></a>
        </div>
        <div>
            <a href="#"><i class="fab fa-facebook-f text-white mr-2"></i></a>
            <a href="#"><i class="fab fa-twitter text-white mr-2"></i></a>
            <a href="#"><i class="fab fa-linkedin text-white mr-2"></i></a>
            <a href="#"><i class="fab fa-instagram text-white mr-2"></i></a>
        </div>
    {% else %}
        <div>
            <a href="{% url 'logout' %}" class="text-uppercase text-dark text-decoration-none small-text">Sign out <i
                    class="fa fa-sign-out-alt"></i></a>
        </div>
        <div class="small-text mt-1 mt-md-0">
            Welcome, <strong>{{ user.first_name }}</strong>
        </div>
    {% endif %}
</div>