blood/urls.py
from django.urls import path
from django.views.generic import ListView
from .models import Blood

app_name = 'blood'

urlpatterns = [
    path('', ListView.as_view(model=Blood), name='home'),
]

hmsproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
    path('patients/', include('patients.urls')),
    path('blood/', include('blood.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patients/urls.py
from django.urls import path

from patients import views
from .views import HomeView, CaseDetailView

app_name = 'patients'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('cases/<int:pk>/', CaseDetailView.as_view(), name='case-detail'),
    # path('payments/', views.PaymentView.as_view(), name='payments')
]

patients/models.py
from django.contrib.auth.models import User
from django.db import models
from blood.models import Blood
from doctors.models import Doctor


class UserProfile(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Others'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    photo = models.ImageField(upload_to='patients/images/')
    age = models.IntegerField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    address = models.TextField()
    phone_number = models.CharField(max_length=10)
    blood_group = models.ForeignKey(Blood, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.user.username


class PatientInstance(models.Model):
    patient = models.ForeignKey(User, on_delete=models.CASCADE)
    mrd_number = models.CharField(max_length=20, unique=True)
    diagnosed_case = models.TextField()
    medical_history = models.TextField()
    room_number = models.CharField(max_length=10, help_text='Either room number or ward number.')
    consulting_doctor = models.ForeignKey(Doctor, on_delete=models.DO_NOTHING)
    active = models.BooleanField(default=False)
    pay_now = models.BooleanField(default=False)

    def __str__(self):
        return self.mrd_number


class BillCategory(models.Model):
    class Meta:
        verbose_name_plural = 'Bill Categories'

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class BillDetail(models.Model):
    patient_instance = models.ForeignKey(PatientInstance, on_delete=models.CASCADE)
    bill_number = models.CharField(max_length=20)
    bill_category = models.ForeignKey(BillCategory, on_delete=models.DO_NOTHING)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    bill_image = models.ImageField(upload_to='bills/images/')

    def __str__(self):
        return self.bill_number


class Order(models.Model):
    token = models.CharField(max_length=256)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    email_address = models.EmailField()
    created_at = models.DateTimeField(auto_now_add=True)
    billing_name = models.CharField(max_length=128)
    billing_address = models.CharField(max_length=128)
    billing_city = models.CharField(max_length=128)
    billing_postcode = models.CharField(max_length=6)
    billing_country = models.CharField(max_length=128)
    shipping_name = models.CharField(max_length=128)
    shipping_address = models.CharField(max_length=128)
    shipping_city = models.CharField(max_length=128)
    shipping_postcode = models.CharField(max_length=6)
    shipping_country = models.CharField(max_length=128)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.billing_name

patients/views.py
import stripe
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic import View

from .models import UserProfile, BillDetail, PatientInstance, Order


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'patients/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cases'] = PatientInstance.objects.all().filter(patient=self.request.user).order_by('-pk')
        return context


class CaseDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = PatientInstance
    template_name = 'patients/case-detail.html'

    def test_func(self):
        patient_object = PatientInstance.objects.get(pk=self.kwargs.get('pk'))
        return patient_object.patient.pk == self.request.user.pk

    def get_context_data(self, **kwargs):
        """
            Commented lines are related to payment gateway! Payment gateway is disabled.
        """
        context = super().get_context_data(**kwargs)
        total_amount = 0
        # description = 'Bill Payment'
        bills = BillDetail.objects.all().filter(patient_instance=self.object.pk)
        for bill in bills:
            total_amount += bill.amount
        context['bills'] = bills
        context['bill_amount'] = total_amount
        # context['stripe_total'] = total_amount*100
        # self.request.session['total'] = str(total_amount)
        # context['data_description'] = description
        # self.request.session['description'] = description
        # context['data_key'] = settings.STRIPE_PUBLISHABLE_KEY
        return context


"""
    PaymentView class represents payment gateway. It is currently disabled.
"""
# class PaymentView(View):
#     def post(self, request, *args, **kwargs):
#         stripe_total = int(self.request.session.get('total') * 100)
#         print(stripe_total)
#         stripe.api_key = settings.STRIPE_SECRET_KEY
#         try:
#             stripe_token = request.POST.get('stripeToken')
#             stripe_email = request.POST.get('stripeEmail')
#             stripe_billing_name = request.POST.get('stripeBillingName')
#             stripe_billing_address = request.POST.get('stripeBillingAddressLine1')
#             stripe_billing_city = request.POST.get('stripeBillingAddressCity')
#             stripe_billing_postcode = request.POST.get('stripeBillingAddressZip')
#             stripe_billing_country = request.POST.get('stripeBillingAddressCountryCode')
#             stripe_shipping_name = request.POST.get('stripeShippingName')
#             stripe_shipping_address = request.POST.get('stripeShippingAddressLine1')
#             stripe_shipping_city = request.POST.get('stripeShippingAddressCity')
#             stripe_shipping_postcode = request.POST.get('stripeShippingAddressZip')
#             stripe_shipping_country = request.POST.get('stripeShippingAddressCountryCode')
#
#             new_customer = stripe.Customer.create(
#                 source=stripe_token,
#                 email=stripe_email
#             )
#             stripe.Charge.create(
#                 customer=new_customer.id,
#                 amount=stripe_total,
#                 description=self.request.session.get('description'),
#                 currency='inr'
#             )
#             ''' Create new order '''
#             try:
#                 new_order = Order.objects.create(
#                     token=stripe_token,
#                     total=request.session.get('total'),
#                     email_address=stripe_email,
#                     billing_name=stripe_billing_name,
#                     billing_address=stripe_billing_address,
#                     billing_city=stripe_billing_city,
#                     billing_postcode=stripe_billing_postcode,
#                     billing_country=stripe_billing_country,
#                     shipping_name=stripe_shipping_name,
#                     shipping_address=stripe_shipping_address,
#                     shipping_city=stripe_shipping_city,
#                     shipping_postcode=stripe_shipping_postcode,
#                     shipping_country=stripe_shipping_country,
#                     user=request.user
#                 )
#                 current_patient = PatientInstance.objects.get(user=request.user)
#                 current_patient.pay_now = False
#                 current_patient.save()
#                 messages.success(request, f'Thank you for placing online. Your discharge ID is {new_order.id}.')
#                 return redirect('order-detail', pk=new_order.id)
#             except ObjectDoesNotExist:
#                 raise Http404
#         except stripe.error.CardError as e:
#             raise Http404

patients/templates/patients/bills.html
{% extends 'layouts/base.html' %}
{% block title %}Bills{% endblock %}
{% block content %}
    <section id="patient-bills" class="py-4">
        {% for bill in bills %}

        {% endfor %}
    </section>
{% endblock %}

patients/templates/patients/case-detail.html
{% extends 'layouts/base.html' %}
{% block title %}Case Detail{% endblock %}
{% block content %}
    <section id="patient-detail" class="py-4">
        <div class="container">
            <div class="row bg-info p-4">
                <div class="col-md-6 border border-dark pt-2">
                    <h3>Personal Information</h3>
                    <p class="lead">Full Name:
                        <strong>{{ object.patient.first_name }} {{ object.patient.last_name }}</strong></p>
                    <p class="lead">Age & Gender: <strong>
                        {{ object.patient.profile.age }}{{ object.patient.profile.gender }}</strong></p>
                    <p class="lead">Address: <strong>{{ object.patient.profile.address }}</strong></p>
                    <p class="lead">Phone Number: <strong>{{ object.patient.profile.phone_number }}</strong></p>
                    <p class="lead">Blood Group: <strong>{{ object.patient.profile.blood_group }}</strong></p>
                </div>
                <div class="col-md-6 border border-dark pt-2">
                    <h3>Admitted Case</h3>
                    <p class="lead">MRD Number: <strong>{{ object.mrd_number }}</strong></p>
                    <p class="lead">Medical History: <strong>{{ object.medical_history }}</strong></p>
                    <p class="lead">Diagnosed Case: <strong>{{ object.diagnosed_case }}</strong></p>
                    <p class="lead">Consulting Doctor: <strong>{{ object.consulting_doctor }}</strong></p>
                    <p class="lead">Room/Ward Number: <strong>{{ object.room_number }}</strong></p>
                </div>
            </div>
            <!-- Bills -->
            <div id="bills" class="row border border-dark bg-dark text-white">
                <div class="col-md-12 text-center">
                    <h2 class="p-2">Bills</h2>
                    <hr class="bg-light">
                </div>
                {% for bill in bills %}
                    <div class="col-md-4">
                        <div class="card mb-3 bg-light text-dark custom-card">
                            <div class="card-header bg-dark text-center text-white border border-light lead">Bill
                                Number: {{ bill.bill_number }}</div>
                            <div class="card-body">
                                <p class="card-title">Category: {{ bill.bill_category }}</p>
                                <p class="card-title">Amount: {{ bill.amount }}</p>
                                <p class="card-title"><a class="text-dark font-weight-bold"
                                                         href="{{ bill.bill_image.url }}">Download Bill</a></p>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="col-md-12"><p class="lead text-center">No bills found!</p></div>
                {% endfor %}
            </div>
            {% if bills %}
                <div class="row bg-info text-dark p-3 font-weight-bold">
                    <div class="col-md-6 text-right text-md-left align-self-md-center">
                        Grand Total
                    </div>
                    <div class="col-md-6 text-right">
                        <span>₹{{ bill_amount }}</span><br>
                        {% if object.pay_now %}
                            {% comment %}
                            Payment Gateway currently disabled!
                            <form method="POST">
                            {% csrf_token %}
                            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                    data-key="{{ data_key }}"
                                    data-name="Patient Discharge"
                                    data-description="{{ data_description }}"
                                    data-amount="{{ stripe_total }}"
                                    data-locale="auto"
{#                                    data-image="{% static 'images/logo.png' %}"#}
                                    data-currency="inr"
                                    data-shipping-address="true"
                                    data-billing-address="true"
                                    data-zip-code="true">
                            </script>
                        </form>
                        {% endcomment %}
                            <button class="btn btn-dark">Pay Now</button>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        </div>
    </section>
{% endblock %}

patients/templates/patients/home.html
{% extends 'layouts/base.html' %}
{% block title %}Welcome{% endblock %}
{% block content %}
    <section id="patient-home" class="py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-9 order-2 order-md-1">
                    <p class="lead">Full Name: <strong>{{ user.first_name }} {{ user.last_name }}</strong></p>
                    <p class="lead">Age & Gender: <strong>{{ user.profile.age }}{{ user.profile.gender }}</strong></p>
                    <p class="lead">Address: <strong>{{ user.profile.address }}</strong></p>
                    <p class="lead">Phone Number: <strong>{{ user.profile.phone_number }}</strong></p>
                    <p class="lead">Blood Group: <strong>{{ user.profile.blood_group.group }}</strong></p>
                    {#                    <p class="lead">Medical History: <strong>{{ user.profile.medical_history }}</strong></p>#}
                    {#                    <p class="lead">Diagnosed Case: <strong>{{ user.profile.diagnosed_case }}</strong></p>#}
                    {#                    <p class="lead">Consulting Doctor: <strong>{{ user.profile.consulting_doctor }}</strong></p>#}
                    {#                    <p class="lead">Room/Ward Number: <strong>{{ user.profile.room_number }}</strong></p>#}
                </div>
                <div class="col-md-3 align-self-center order-1 order-md-2">
                    <img src="{{ user.profile.photo.url }}" alt="{{ user.first_name }}" class="img-fluid">
                    <hr class="d-sm-block d-md-none border border-dark">
                </div>
            </div>
            <div class="border border-dark p-3 mt-3 bg-info">
                <h2 class="text-center">Cases</h2>

                <ul class="list-group p-2">
                    {% for case in cases %}
                        <li class="list-group-item bg-dark text-white">
                            <div class="row">
                                <div class="col-md-5">
                                    {{ case.mrd_number }}
                                    {% if case.active %}
                                        <span class="badge badge-secondary">Active</span>
                                    {% endif %}
                                </div>
                                <div class="col-md-5">{{ case.consulting_doctor }}</div>
                                <div class="col-md-2 text-right">
                                    <a href="{% url 'patients:case-detail' case.pk %}" class="text-info"><i class="fas fa-eye"></i></a>
                                </div>
                            </div>
                        </li>
                    {% empty %}
                        <p class="lead text-center">No cases found!</p>
                    {% endfor %}
                </ul>

            </div>
        </div>
    </section>
{% endblock %}